services:
  - type: web
    name: translator-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: AIVEN_POSTGRES
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_TRANSLATION_MODEL
        value: gpt-5.1
